name: Build APK

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'zulu'
          cache: 'gradle'

      - name: Build project with Gradle
        run: chmod +x ./gradlew && ./gradlew app:assembleDebug

      - name: Upload apk as artifact
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: |
            app/build/outputs/apk/debug/app-debug.apk
